import { SpecificationInput } from '../models/specification-input';
import { GeneratedTestScenario } from '../models/test-scenario';
import { JobResults } from '../models/job';
import { JiraConfig } from '../models/config';
import { normalizeInput } from './normalizer';
import { buildPrompt } from './prompt-builder';
import { invokeLLM } from './llm-client';
import { validateScenarios } from './validator';
import { formatForJira } from './jira-formatter';
import { saveGeneratedScenarios, saveNeedsReviewScenarios, saveMetadata } from '../storage/file-manager';
import logger, { createContextLogger } from '../utils/logger';

export async function executePipeline(
  input: SpecificationInput,
  jiraConfig: JiraConfig,
  jobId: string
): Promise<JobResults> {
  const contextLogger = createContextLogger({
    job_id: jobId,
    confluence_page_id: input.confluence_page_id,
    parent_jira_issue_id: input.metadata.parent_jira_issue_id,
  });

  contextLogger.info('Pipeline execution started');

  const pipelineStartTime = Date.now();

  try {
    const step1Start = Date.now();
    contextLogger.info('Pipeline Step 1: Input normalization');
    const normalizedInput = await normalizeInput(input);
    const step1Duration = Date.now() - step1Start;
    contextLogger.info('Pipeline Step 1 completed', { duration_ms: step1Duration });

    const step2Start = Date.now();
    contextLogger.info('Pipeline Step 2: LLM prompt preparation');
    const promptMessages = buildPrompt(normalizedInput);
    const step2Duration = Date.now() - step2Start;
    contextLogger.info('Pipeline Step 2 completed', { duration_ms: step2Duration });

    const step3Start = Date.now();
    contextLogger.info('Pipeline Step 3: LLM invocation');
    const generatedScenarios = await invokeLLM(promptMessages, normalizedInput, jobId);
    const step3Duration = Date.now() - step3Start;
    contextLogger.info('Pipeline Step 3 completed', {
      duration_ms: step3Duration,
      scenario_count: generatedScenarios.length,
    });

    if (generatedScenarios.length === 0) {
      contextLogger.warn('No scenarios generated by LLM');
      return {
        total_scenarios: 0,
        validated_scenarios: 0,
        needs_review_scenarios: 0,
        scenarios: [],
      };
    }

    const step4Start = Date.now();
    contextLogger.info('Pipeline Step 4: Output validation');
    const validatedScenarios = await validateScenarios(generatedScenarios, normalizedInput, jobId);
    const step4Duration = Date.now() - step4Start;
    contextLogger.info('Pipeline Step 4 completed', { duration_ms: step4Duration });

    const validatedCount = validatedScenarios.filter(s => s.validation_status === 'validated').length;
    const needsReviewCount = validatedScenarios.filter(s => s.validation_status === 'needs_review').length;

    const validatedOnly = validatedScenarios.filter(s => s.validation_status === 'validated');
    const needsReviewOnly = validatedScenarios.filter(s => s.validation_status === 'needs_review');

    const confluencePageId = input.confluence_page_id || 'manual-input';

    if (validatedOnly.length > 0) {
      await saveGeneratedScenarios(confluencePageId, validatedOnly);
    }

    if (needsReviewOnly.length > 0) {
      await saveNeedsReviewScenarios(confluencePageId, needsReviewOnly);
    }

    await saveMetadata(confluencePageId, {
      timestamp: new Date().toISOString(),
      specification_version: input.confluence_version || '1',
      confluence_page_id: confluencePageId,
    });

    const step5Start = Date.now();
    contextLogger.info('Pipeline Step 5: Jira preparation');
    await formatForJira(validatedScenarios, jiraConfig, confluencePageId, jobId);
    const step5Duration = Date.now() - step5Start;
    contextLogger.info('Pipeline Step 5 completed', { duration_ms: step5Duration });

    const pipelineDuration = Date.now() - pipelineStartTime;

    contextLogger.info('Pipeline execution completed successfully', {
      total_duration_ms: pipelineDuration,
      total_scenarios: validatedScenarios.length,
      validated: validatedCount,
      needs_review: needsReviewCount,
    });

    return {
      total_scenarios: validatedScenarios.length,
      validated_scenarios: validatedCount,
      needs_review_scenarios: needsReviewCount,
      scenarios: validatedScenarios,
    };
  } catch (error) {
    const pipelineDuration = Date.now() - pipelineStartTime;

    contextLogger.error('Pipeline execution failed', {
      error: (error as Error).message,
      stack: (error as Error).stack,
      duration_ms: pipelineDuration,
    });

    throw error;
  }
}
